server.port=8080
spring.application.name=com.SpringNestedJSON
spring.datasourece.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/developer
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

