server.port=8080
spring.application.name=SpringSocialAuth
spring.security.oauth2.client.registration.google.client-id=900963206012-inu74p884i4qgin0queei1mdg6og4116.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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c
